### ISSUE TITLE
Black screen on some device (Android) 

### ISSUE THREAD

**Issue by MapleNoise** [Knightro63/three_js#17]
Hi,

I've a black screen on Pixel 7 Android 14, sometimes one frame appear and black screen, or sometimes the frame freezed.
`threeJs.addAnimationEvent` seems not to be called.

No problem with my Samsung S10 Android 10.

• I'm testing with your example sample and use Android Studio Iguana 2023.2.1 

My flutter version angle is flutter_angle 0.0.6

On log I've : 
```I/FlutterWegGL( 1365): OpenGL initialized: Vendor:ARM renderer: Mali-G710 Version: OpenGL ES 3.2 v1.r47p0-01eac0.cd24a10f5ddffa4cfe272051060e786b
D/OpenGLManager( 1365): Successfully initialized GL in plugin
I/flutter ( 1365): EGL version: 1.5
I/flutter ( 1365): DONE
I/FlutterAngle( 1365): Created a new texture 1078x2336
D/ProfileInstaller( 1365): Installing profile for fr.lmstudio.threebox
##NOTHING HAPPEN AFTER THAT

Flutter doctor : 
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.3 23D56 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (3 available)
[✓] Network resources
• No issues found!

**Comment by yashkhokhar28** [comment]
can you please provide video or screenshots?

**Comment by Knightro63** [comment]
Hi @MapleNoise,

Are you running this on a real device or simulator? 

Also do you know which examples are giving you this issue, so I can try to narrow the issue down.

Thank you

**Comment by MapleNoise** [comment]
Thanks you for your reply @Knightro63,

I test on real device and my sample is very simple :
With my Pixel 7 `addAnimationEvent` is only called 1 times or 2 times, after that it stops

```
import 'dart:math';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:three_js/three_js.dart' as three;
import 'package:threebox/models/Coin.dart';
import 'package:threebox/models/Player.dart';

class MyHomePage extends StatefulWidget {

  MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late three.ThreeJS threeJs;
  late three.OrbitControls controls;
  late three.AnimationMixer mixer;

  @override
  void initState() {
    threeJs = three.ThreeJS(
      onSetupComplete: (){setState(() {});},
      setup: setup,
      settings: three.Settings(
          clearAlpha: 0,
          clearColor: 0xffffff,

      ),
    );
    super.initState();
  }
  @override
  void dispose() {
    threeJs.dispose();
    three.loading.clear();
    joystick?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return threeJs.build();
  }

  Map<LogicalKeyboardKey,bool> keyStates = {
    LogicalKeyboardKey.space: false,
    LogicalKeyboardKey.arrowUp: false,
    LogicalKeyboardKey.arrowLeft: false,
    LogicalKeyboardKey.arrowDown: false,
    LogicalKeyboardKey.arrowRight: false,
  };

  double gravity = 30;
  int stepsPerFrame = 5;

  Future<void> setup() async {
    threeJs.camera = three.PerspectiveCamera(45, threeJs.width / threeJs.height, 1, 2200);
    threeJs.camera.position.setValues(3, 6, 10);
    controls = three.OrbitControls(threeJs.camera, threeJs.globalKey);
    threeJs.scene = three.Scene();
    threeJs.scene.background = three.Color.fromHex32(0xffffff);

    final ambientLight = three.AmbientLight(0xffffff, 0.9);
    threeJs.scene.add(ambientLight);

    final pointLight = three.PointLight(0xffffff, 0.8);

    pointLight.position.setValues(0, 0, 0);

    threeJs.camera.add(pointLight);
    threeJs.scene.add(threeJs.camera);

    threeJs.camera.lookAt(threeJs.scene.position);

    three.GLTFLoader loader = three.GLTFLoader().setPath('assets/');
    three.GLTFData? result = await loader.fromAsset( 'dash.glb' );

    final object = result!.scene;
    threeJs.scene.add(object);
    mixer = three.AnimationMixer(object);
    mixer.clipAction(result.animations![4], null, null)!.play();

    threeJs.addAnimationEvent((dt){
      print("here");
      mixer.update(dt);
      controls.update();
      print("here2");
    });
  }
}

**Comment by Knightro63** [comment]
Hi @MapleNoise ,

Take a look at [this](https://github.com/Knightro63/three_js/issues/36) error. I think it will fix your issue.

**Comment by MapleNoise** [comment]
Hi, 
Current version :
 • three_js 0.1.0+1
 • flutter_angle 0.2.1
On Flutter 3.29.3

I download  CMake 3.31.4 from SDK Manager

But like [in this comment](https://github.com/Knightro63/three_js/issues/36#issuecomment-2706756652) I have :

Have I forgotten anything?

````
E/flutter (17927): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter (17927): #0      List._setIndexed (dart:core-patch/array.dart:189:48)
E/flutter (17927): #1      List.[]= (dart:core-patch/array.dart:184:5)
E/flutter (17927): #2      WebGLBindingStates.enableAttributeAndDivisor (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:227:18)
E/flutter (17927): #3      WebGLBindingStates.enableAttribute (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:219:5)
E/flutter (17927): #4      WebGLBindingStates.setupVertexAttributes (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:356:17)
E/flutter (17927): #5      WebGLBindingStates.setup (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:57:7)
E/flutter (17927): #6      WebGLRenderer.renderBufferDirect (package:three_js_core/renderers/web_gl_renderer.dart:592:19)
E/flutter (17927): #7      WebGLRenderer.renderObject (package:three_js_core/renderers/web_gl_renderer.dart:1174:7)
E/flutter (17927): #8      WebGLRenderer.renderObjects (package:three_js_core/renderers/web_gl_renderer.dart:1134:9)
E/flutter (17927): #9      WebGLRenderer.renderScene (package:three_js_core/renderers/web_gl_renderer.dart:1013:35)
E/flutter (17927): #10     WebGLRenderer.render (package:three_js_core/renderers/web_gl_renderer.dart:860:7)
E/flutter (17927): #11     ThreeJS.render (package:three_js_core/others/three_viewer.dart:184:17)
E/flutter (17927): #12     ThreeJS.animate (package:three_js_core/others/three_viewer.dart:167:7)
E/flutter (17927): #13     Ticker._tick (package:flutter/src/scheduler/ticker.dart:277:12)
E/flutter (17927): #14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442:15)
E/flutter (17927): #15     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1273:11)
E/flutter (17927): #16     _LinkedHashMapMixin.forEach (dart:_compact_hash:763:13)
E/flutter (17927): #17     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1271:17)
E/flutter (17927): #18     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1187:5)
E/flutter (17927): #19     _invoke1 (dart:ui/hooks.dart:332:13)
E/flutter (17927): #20     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:410:5)
E/flutter (17927): #21     _beginFrame (dart:ui/hooks.dart:277:31)

**Comment by MapleNoise** [comment]
I always use one of your example, I try multiple example but nothing works on my Pixel 7 and now Samsung S10.

Before update pub it worked on my Samsung S10.

`````
import 'dart:async';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:three_js/three_js.dart' as three;
import 'package:three_js_geometry/three_js_geometry.dart';

class MyHomePage extends StatefulWidget {

  const MyHomePage({super.key});

  @override
  createState() => _State();
}

class _State extends State<MyHomePage> {
  List<int> data = List.filled(60, 0, growable: true);
  late Timer timer;
  late three.ThreeJS threeJs;

  @override
  void initState() {
    timer = Timer.periodic(const Duration(seconds: 1), (t){
      setState(() {
        data.removeAt(0);
        data.add(threeJs.clock.fps);
      });
    });
    threeJs = three.ThreeJS(
      onSetupComplete: (){setState(() {});},
      setup: setup,
    );
    super.initState();
  }
  @override
  void dispose() {
    controls.dispose();
    timer.cancel();
    threeJs.dispose();
    three.loading.clear();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Stack(
          children: [
            threeJs.build(),
            //Statistics(data: data)
          ],
        )
    );
  }

  late three.OrbitControls controls ;

  Future<void> setup() async {
    threeJs.camera = three.PerspectiveCamera( 45, threeJs.width/threeJs.height, 1, 1000 );
    threeJs.camera.position.setValues( 0, 10, 30 );

    threeJs.scene = three.Scene();
    threeJs.scene.background = three.Color.fromHex32( 0x222244 );
    threeJs.scene.fog = three.Fog( 0x222244, 50, 100 );

    threeJs.scene.add( three.AmbientLight( 0x444444,0.4) );

    final spotLight = three.SpotLight( 0xff3333, 10 );
    spotLight.angle = math.pi / 5;
    spotLight.penumbra = 0.3;
    spotLight.position.setValues( 8, 10, 5 );
    spotLight.castShadow = true;
    spotLight.shadow?.camera?.near = 8;
    spotLight.shadow?.camera?.far = 200;
    spotLight.shadow?.mapSize.width = 256;
    spotLight.shadow?.mapSize.height = 256;
    spotLight.shadow?.bias = - 0.002;
    spotLight.shadow?.radius = 4;
    threeJs.scene.add( spotLight );

    final dirLight = three.DirectionalLight( 0x3333ff, 0.8 );
    dirLight.position.setValues( 3, 12, 17 );
    dirLight.castShadow = true;
    dirLight.shadow?.camera?.near = 0.1;
    dirLight.shadow?.camera?.far = 500;
    dirLight.shadow?.camera?.right = 17;
    dirLight.shadow?.camera?.left = - 17;
    dirLight.shadow?.camera?.top	= 17;
    dirLight.shadow?.camera?.bottom = - 17;
    dirLight.shadow?.mapSize.width = 512;
    dirLight.shadow?.mapSize.height = 512;
    dirLight.shadow?.radius = 4;
    dirLight.shadow?.bias = - 0.005;

    final dirGroup = three.Group();
    dirGroup.add( dirLight );
    threeJs.scene.add( dirGroup );

    // Geometry

    final geometry = TorusKnotGeometry( 25, 8, 75, 20 );
    final material = three.MeshPhongMaterial.fromMap( {
      'color': 0x999999,
      'shininess': 0,
      'specular': 0x222222
    } );

    final torusKnot = three.Mesh( geometry, material );
    torusKnot.scale.scale( 1 / 18 );
    torusKnot.position.y = 3;
    torusKnot.castShadow = true;
    torusKnot.receiveShadow = true;
    threeJs.scene.add( torusKnot );

    final cylinderGeometry = CylinderGeometry( 0.75, 0.75, 7, 32 );

    final pillar1 = three.Mesh( cylinderGeometry, material );
    pillar1.position.setValues( 8, 3.5, 8 );
    pillar1.castShadow = true;
    pillar1.receiveShadow = true;

    final pillar2 = pillar1.clone();
    pillar2.position.setValues( 8, 3.5, - 8 );
    final pillar3 = pillar1.clone();
    pillar3.position.setValues( - 8, 3.5, 8 );
    final pillar4 = pillar1.clone();
    pillar4.position.setValues( - 8, 3.5, - 8 );

    threeJs.scene.add( pillar1 );
    threeJs.scene.add( pillar2 );
    threeJs.scene.add( pillar3 );
    threeJs.scene.add( pillar4 );

    final planeGeometry = three.PlaneGeometry( 200, 200 );
    final planeMaterial = three.MeshPhongMaterial.fromMap( {
      'color': 0x999999,
      'shininess': 0,
      'specular': 0x111111
    } );

    final ground = three.Mesh( planeGeometry, planeMaterial );
    ground.rotation.x = - math.pi / 2;
    ground.scale.scale( 3 );
    ground.castShadow = true;
    ground.receiveShadow = true;
    threeJs.scene.add( ground );

    threeJs.renderer?.shadowMap.type = three.VSMShadowMap;

    // Mouse control
    controls = three.OrbitControls( threeJs.camera, threeJs.globalKey );
    controls.target.setValues( 0, 2, 0 );


    threeJs.addAnimationEvent((delta){
      final time = DateTime.now().millisecondsSinceEpoch;
      controls.update();

      torusKnot.rotation.x += 0.25 * delta;
      torusKnot.rotation.y += 0.5 * delta;
      torusKnot.rotation.z += 1 * delta;

      dirGroup.rotation.y += 0.7 * delta;
      dirLight.position.z = 17 + math.sin( time * 0.001 ) * 5;
    });
  }
}
`````

**Comment by MapleNoise** [comment]
Yes, it works on emulator changing :

`````
Please Change package:flutter_angle/desktop/angle.dart:121 to this.
_useAngle = result['isEmulator'] == null?_useAngle:!result['isEmulator'];
`````
• On my Samsung S10 I have an infinite circle progress at start.

• On my Pixel 7 it crash after multiples :
`````
E/flutter (17927): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter (17927): #0      List._setIndexed (dart:core-patch/array.dart:189:48)
E/flutter (17927): #1      List.[]= (dart:core-patch/array.dart:184:5)
E/flutter (17927): #2      WebGLBindingStates.enableAttributeAndDivisor (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:227:18)
E/flutter (17927): #3      WebGLBindingStates.enableAttribute (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:219:5)
E/flutter (17927): #4      WebGLBindingStates.setupVertexAttributes (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:356:17)
E/flutter (17927): #5      WebGLBindingStates.setup (package:three_js_core/renderers/webgl/web_gl_binding_states.dart:57:7)
E/flutter (17927): #6      WebGLRenderer.renderBufferDirect (package:three_js_core/renderers/web_gl_renderer.dart:592:19)
E/flutter (17927): #7      WebGLRenderer.renderObject (package:three_js_core/renderers/web_gl_renderer.dart:1174:7)
E/flutter (17927): #8      WebGLRenderer.renderObjects (package:three_js_core/renderers/web_gl_renderer.dart:1134:9)
E/flutter (17927): #9      WebGLRenderer.renderScene (package:three_js_core/renderers/web_gl_renderer.dart:1013:35)
E/flutter (17927): #10     WebGLRenderer.render (package:three_js_core/renderers/web_gl_renderer.dart:860:7)
E/flutter (17927): #11     ThreeJS.render (package:three_js_core/others/three_viewer.dart:184:17)
E/flutter (17927): #12     ThreeJS.animate (package:three_js_core/others/three_viewer.dart:167:7)
E/flutter (17927): #13     Ticker._tick (package:flutter/src/scheduler/ticker.dart:277:12)
E/flutter (17927): #14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442:15)
E/flutter (17927): #15     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1273:11)
E/flutter (17927): #16     _LinkedHashMapMixin.forEach (dart:_compact_hash:763:13)
E/flutter (17927): #17     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1271:17)
E/flutter (17927): #18     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1187:5)
E/flutter (17927): #19     _invoke1 (dart:ui/hooks.dart:332:13)
E/flutter (17927): #20     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:410:5)
E/flutter (17927): #21     _beginFrame (dart:ui/hooks.dart:277:31)
``````

**Comment by Knightro63** [comment]
Hi @MapleNoise,

This [issue](https://github.com/Knightro63/three_js/issues/53) also describes the same thing.

It seems to be a Vulkan issue with flutter_angle. I will ask for help from that team.

**Comment by Knightro63** [comment]
Hi @MapleNoise,

I was able to reproduce the error on a newer updated device. I believe the error is resolved. Please updated three_js to 0.1.1.

Sorry for the inconvenience.
