### ISSUE TITLE
PlatformException(no texture width, no texture width, 0, null) when running in release mode

### ISSUE THREAD

**Issue by AliGanjehei** [Knightro63/three_js#19]
when i run the project as release mode this error appears

```
I/FlutterWegGL(18144): OpenGL initialized: Vendor:Qualcomm renderer: Adreno (TM) 660 Version: OpenGL ES 3.2 V@0530.0 (GIT@12ae96cb63, I409bbc12eb, 1694603898) (Date:09/13/23)
I/flutter (18144): EGL version: 1.5
I/flutter (18144): DONE
E/flutter (18144): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(no texture width, no texture width, 0, null)
E/flutter (18144): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
E/flutter (18144): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
E/flutter (18144): <asynchronous suspension>
E/flutter (18144): #2      FlutterAngle.createTexture (package:flutter_angle/desktop/angle.dart:298)
E/flutter (18144): <asynchronous suspension>
E/flutter (18144): #3      ThreeJS.initPlatformState (package:three_js_core/others/three_viewer.dart:278)
E/flutter (18144): <asynchronous suspension>
E/flutter (18144):
```

**Comment by Knightro63** [comment]
Hi @AliGanjehei,

I am looking into the issue but have not had any success replicating it. 
I will check a few more things and see if I can get a similar result.

Thank you

**Comment by AliGanjehei** [comment]
@Knightro63 thank you
